stages:
  # get_data:
  #   cmd: dvc pull
  #   outs:
  #   - data/raw/raw_data.csv
  process_data:
    cmd: python3 prepare.py
    deps:
    - prepare.py
    - data/raw/raw_data.csv
    outs:
    - data/processed/data_processed.plk
  train_model:
    cmd: python3 train.py
    deps:
    - train.py
    - data/processed/data_processed.plk
    metrics:
    - metrics.txt:
        cache: false
