stages:
  # get_dataset:
  #   cmd: python3 pipeline_steps/get_dataset.py
  #   deps:
  #   - pipeline_steps/get_dataset.py
  #   outs:
  #   - data/raw/raw_data.csv
  prepare:
    cmd: python3 pipeline_steps/prepare.py
    deps:
    - data/raw/raw_data.csv
    - pipeline_steps/prepare.py
    params:
    - prepare.how_many_generated
    outs:
    - data/processed/data_processed.plk
  train:
    cmd: python3 pipeline_steps/train.py
    deps:
    - data/processed/data_processed.plk
    - pipeline_steps/train.py
    params:
    - train.for_test_procentage
    - train.for_train_procentage
    outs:
    - src/models

    metrics:
    - metrics.json:
        cache: false
