stages:
  get_data:
    cmd: wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TKxABVonvgiE2oBgTKB6oOxXkynqjFth' -O data/raw/raw_data.csv 
    outs:
    - data/raw/raw_data.csv
  process_data:
    cmd: python3 prepare.py
    deps:
    - prepare.py
    - data/raw/raw_data.csv
    outs:
    - data/processed/data_processed.plk
  train_model:
    cmd: python3 train.py
    deps:
    - train.py
    - data/processed/data_processed.plk
    metrics:
    - metrics.txt:
        cache: false
