stages:
  get_data:
    cmd: python pipeline_steps/get_data.py
    deps:
    - get_data.py
    outs:
    - data/raw/raw_data.csv
  process_data:
    cmd: python pipeline_steps/prepare.py
    deps:
    - pipeline_steps/prepare.py
    - data/raw/raw_data.csv
    outs:
    - data/processed/data_processed.plk
  train_model:
    cmd: python pipeline_steps/train.py
    deps:
    - pipeline_steps/train.py
    - data_processed.plk
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cache: false
