name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python -m spacy download ro_core_news_lg
          dvc pull
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md dev > report.md

          cml-send-comment report.md 